<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Message extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Message_model');
    } 

    /*
     * Listing of messages
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('message/index?');
        $config['total_rows'] = $this->Message_model->get_all_messages_count();
        $this->pagination->initialize($config);

        $data['messages'] = $this->Message_model->get_all_messages($params);
        
        $data['_view'] = 'message/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new message
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'message_client_recepteur' => $this->input->post('message_client_recepteur'),
				'message_objet' => $this->input->post('message_objet'),
				'message_statut' => $this->input->post('message_statut'),
				'message_created_at' => $this->input->post('message_created_at'),
				'message_created_by' => $this->input->post('message_created_by'),
				'message_updated_at' => $this->input->post('message_updated_at'),
				'message_updated_by' => $this->input->post('message_updated_by'),
				'message_deleted_at' => $this->input->post('message_deleted_at'),
				'message_deleted_by' => $this->input->post('message_deleted_by'),
				'message_description' => $this->input->post('message_description'),
            );
            
            $message_id = $this->Message_model->add_message($params);
            redirect('message/index');
        }
        else
        {
			$this->load->model('Client_model');
			$data['all_clients'] = $this->Client_model->get_all_clients();
            
            $data['_view'] = 'message/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a message
     */
    function edit($message_uid)
    {   
        // check if the message exists before trying to edit it
        $data['message'] = $this->Message_model->get_message($message_uid);
        
        if(isset($data['message']['message_uid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'message_client_recepteur' => $this->input->post('message_client_recepteur'),
					'message_objet' => $this->input->post('message_objet'),
					'message_statut' => $this->input->post('message_statut'),
					'message_created_at' => $this->input->post('message_created_at'),
					'message_created_by' => $this->input->post('message_created_by'),
					'message_updated_at' => $this->input->post('message_updated_at'),
					'message_updated_by' => $this->input->post('message_updated_by'),
					'message_deleted_at' => $this->input->post('message_deleted_at'),
					'message_deleted_by' => $this->input->post('message_deleted_by'),
					'message_description' => $this->input->post('message_description'),
                );

                $this->Message_model->update_message($message_uid,$params);            
                redirect('message/index');
            }
            else
            {
				$this->load->model('Client_model');
				$data['all_clients'] = $this->Client_model->get_all_clients();

                $data['_view'] = 'message/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The message you are trying to edit does not exist.');
    } 

    /*
     * Deleting message
     */
    function remove($message_uid)
    {
        $message = $this->Message_model->get_message($message_uid);

        // check if the message exists before trying to delete it
        if(isset($message['message_uid']))
        {
            $this->Message_model->delete_message($message_uid);
            redirect('message/index');
        }
        else
            show_error('The message you are trying to delete does not exist.');
    }
    
}
