<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Temoigange extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Temoigange_model');
    } 

    /*
     * Listing of temoiganges
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('temoigange/index?');
        $config['total_rows'] = $this->Temoigange_model->get_all_temoiganges_count();
        $this->pagination->initialize($config);

        $data['temoiganges'] = $this->Temoigange_model->get_all_temoiganges($params);
        
        $data['_view'] = 'temoigange/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new temoigange
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'temoigange_nom' => $this->input->post('temoigange_nom'),
				'temoigange_email' => $this->input->post('temoigange_email'),
				'temoigange_profession' => $this->input->post('temoigange_profession'),
				'temoigange_statut' => $this->input->post('temoigange_statut'),
				'temoigange_created_at' => $this->input->post('temoigange_created_at'),
				'temoigange_created_by' => $this->input->post('temoigange_created_by'),
				'temoigange_updated_at' => $this->input->post('temoigange_updated_at'),
				'temoigange_updated_by' => $this->input->post('temoigange_updated_by'),
				'temoigange_deleted_at' => $this->input->post('temoigange_deleted_at'),
				'temoigange_deleted_by' => $this->input->post('temoigange_deleted_by'),
				'temoigange_description' => $this->input->post('temoigange_description'),
            );
            
            $temoigange_id = $this->Temoigange_model->add_temoigange($params);
            redirect('temoigange/index');
        }
        else
        {            
            $data['_view'] = 'temoigange/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a temoigange
     */
    function edit($temoigange_uid)
    {   
        // check if the temoigange exists before trying to edit it
        $data['temoigange'] = $this->Temoigange_model->get_temoigange($temoigange_uid);
        
        if(isset($data['temoigange']['temoigange_uid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'temoigange_nom' => $this->input->post('temoigange_nom'),
					'temoigange_email' => $this->input->post('temoigange_email'),
					'temoigange_profession' => $this->input->post('temoigange_profession'),
					'temoigange_statut' => $this->input->post('temoigange_statut'),
					'temoigange_created_at' => $this->input->post('temoigange_created_at'),
					'temoigange_created_by' => $this->input->post('temoigange_created_by'),
					'temoigange_updated_at' => $this->input->post('temoigange_updated_at'),
					'temoigange_updated_by' => $this->input->post('temoigange_updated_by'),
					'temoigange_deleted_at' => $this->input->post('temoigange_deleted_at'),
					'temoigange_deleted_by' => $this->input->post('temoigange_deleted_by'),
					'temoigange_description' => $this->input->post('temoigange_description'),
                );

                $this->Temoigange_model->update_temoigange($temoigange_uid,$params);            
                redirect('temoigange/index');
            }
            else
            {
                $data['_view'] = 'temoigange/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The temoigange you are trying to edit does not exist.');
    } 

    /*
     * Deleting temoigange
     */
    function remove($temoigange_uid)
    {
        $temoigange = $this->Temoigange_model->get_temoigange($temoigange_uid);

        // check if the temoigange exists before trying to delete it
        if(isset($temoigange['temoigange_uid']))
        {
            $this->Temoigange_model->delete_temoigange($temoigange_uid);
            redirect('temoigange/index');
        }
        else
            show_error('The temoigange you are trying to delete does not exist.');
    }
    
}
