<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Article_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get article by article_uid
     */
    function get_article($article_uid)
    {
        //return $this->db->get_where('articles',array('article_uid'=>$article_uid))->row_array();

        $this->db->join('categories','categories.categorie_uid = articles.article_categorie_uid');
        
        $query=$this->db->get_where('articles',array('article_uid'=>$article_uid));
        
        return $query->row_array();
    }
    

    /*
     * Get all articles count
     */
    function get_all_articles_count()
    {
        $this->db->from('articles');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all articles
     */
    function get_all_articles($params = array())
    {
        $this->db->order_by('article_uid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->join('categories','categories.categorie_uid = articles.article_categorie_uid');
        return $this->db->get('articles')->result_array();
    }
        
    /*
     * function to add new article
     */
    function add_article($params)
    {
        $this->db->insert('articles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update article
     */
    function update_article($article_uid,$params)
    {
        $this->db->where('article_uid',$article_uid);
        return $this->db->update('articles',$params);
    }
    
    /*
     * function to delete article
     */
    function delete_article($article_uid)
    {
        return $this->db->delete('articles',array('article_uid'=>$article_uid));
    }
}
