<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category by categorie_uid
     */
    function get_category($categorie_uid)
    {
        return $this->db->get_where('categories',array('categorie_uid'=>$categorie_uid))->row_array();
    }
    
    /*
     * Get all categories count
     */
    function get_all_categories_count()
    {
        $this->db->from('categories');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all categories
     */
    function get_all_categories($params = array())
    {
        $this->db->order_by('categorie_uid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('categories')->result_array();
    }
        
    /*
     * function to add new category
     */
    function add_category($params)
    {
        $this->db->insert('categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update category
     */
    function update_category($categorie_uid,$params)
    {
        $this->db->where('categorie_uid',$categorie_uid);
        return $this->db->update('categories',$params);
    }
    
    /*
     * function to delete category
     */
    function delete_category($categorie_uid)
    {
        return $this->db->delete('categories',array('categorie_uid'=>$categorie_uid));
    }
}
