<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get client by client_uid
     */
    function get_client($client_uid)
    {
        return $this->db->get_where('clients',array('client_uid'=>$client_uid))->row_array();
    }
    
    /*
     * Get all clients count
     */
    function get_all_clients_count()
    {
        $this->db->from('clients');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all clients
     */
    function get_all_clients($params = array())
    {
        $this->db->order_by('client_uid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('clients')->result_array();
    }
        
    /*
     * function to add new client
     */
    function add_client($params)
    {
        $this->db->insert('clients',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update client
     */
    function update_client($client_uid,$params)
    {
        $this->db->where('client_uid',$client_uid);
        return $this->db->update('clients',$params);
    }
    
    /*
     * function to delete client
     */
    function delete_client($client_uid)
    {
        return $this->db->delete('clients',array('client_uid'=>$client_uid));
    }
}
