<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commentaire_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get commentaire by commentaire_uid
     */
    function get_commentaire($commentaire_uid)
    {
        return $this->db->get_where('commentaires',array('commentaire_uid'=>$commentaire_uid))->row_array();
    }
    
    /*
     * Get all commentaires count
     */
    function get_all_commentaires_count()
    {
        $this->db->from('commentaires');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all commentaires
     */
    function get_all_commentaires($params = array())
    {
        $this->db->order_by('commentaire_uid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        
         $this->db->join('articles','articles.article_uid = commentaires.commentaire_article_uid');
        return $this->db->get('commentaires')->result_array();
    }
        
    /*
     * function to add new commentaire
     */
    function add_commentaire($params)
    {
        $this->db->insert('commentaires',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update commentaire
     */
    function update_commentaire($commentaire_uid,$params)
    {
        $this->db->where('commentaire_uid',$commentaire_uid);
        return $this->db->update('commentaires',$params);
    }
    
    /*
     * function to delete commentaire
     */
    function delete_commentaire($commentaire_uid)
    {
        return $this->db->delete('commentaires',array('commentaire_uid'=>$commentaire_uid));
    }
}
