<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Message_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get message by message_uid
     */
    function get_message($message_uid)
    {
        return $this->db->get_where('messages',array('message_uid'=>$message_uid))->row_array();
    }
    
    /*
     * Get all messages count
     */
    function get_all_messages_count()
    {
        $this->db->from('messages');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all messages
     */
    function get_all_messages($params = array())
    {
        $this->db->order_by('message_uid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
         $this->db->join('clients','clients.client_uid = messages.message_client_uid');
        return $this->db->get('messages')->result_array();
    }
        
    /*
     * function to add new message
     */
    function add_message($params)
    {
        $this->db->insert('messages',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update message
     */
    function update_message($message_uid,$params)
    {
        $this->db->where('message_uid',$message_uid);
        return $this->db->update('messages',$params);
    }
    
    /*
     * function to delete message
     */
    function delete_message($message_uid)
    {
        return $this->db->delete('messages',array('message_uid'=>$message_uid));
    }
}
