<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Newsletter_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get newsletter by newsletter_uid
     */
    function get_newsletter($newsletter_uid)
    {
        return $this->db->get_where('newsletters',array('newsletter_uid'=>$newsletter_uid))->row_array();
    }
    
    /*
     * Get all newsletters count
     */
    function get_all_newsletters_count()
    {
        $this->db->from('newsletters');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all newsletters
     */
    function get_all_newsletters($params = array())
    {
        $this->db->order_by('newsletter_uid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('newsletters')->result_array();
    }
        
    /*
     * function to add new newsletter
     */
    function add_newsletter($params)
    {
        $this->db->insert('newsletters',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update newsletter
     */
    function update_newsletter($newsletter_uid,$params)
    {
        $this->db->where('newsletter_uid',$newsletter_uid);
        return $this->db->update('newsletters',$params);
    }
    
    /*
     * function to delete newsletter
     */
    function delete_newsletter($newsletter_uid)
    {
        return $this->db->delete('newsletters',array('newsletter_uid'=>$newsletter_uid));
    }
}
