<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Service_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get service by service_uid
     */
    function get_service($service_uid)
    {
        return $this->db->get_where('services',array('service_uid'=>$service_uid))->row_array();
    }
    
    /*
     * Get all services count
     */
    function get_all_services_count()
    {
        $this->db->from('services');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all services
     */
    function get_all_services($params = array())
    {
        $this->db->order_by('service_uid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('services')->result_array();
    }
        
    /*
     * function to add new service
     */
    function add_service($params)
    {
        $this->db->insert('services',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update service
     */
    function update_service($service_uid,$params)
    {
        $this->db->where('service_uid',$service_uid);
        return $this->db->update('services',$params);
    }
    
    /*
     * function to delete service
     */
    function delete_service($service_uid)
    {
        return $this->db->delete('services',array('service_uid'=>$service_uid));
    }
}
